### PR TITLE
Add missing backtick

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by slavaschmidt** [comment]
Thank you very much!

**Comment by benmccann** [comment]
No problem. Are you guys still planning to work on this project? Just curious because I noticed there haven't been any commits in a few weeks. I'm a big contributor to Play. I'm really time-constrained at the moment, so unfortunately I can't contribute much myself, but I'd be happy to help answer questions from the Play side. I know James has already been helping with that and he's better than I am especially from the Scala side (I use Play Java), but if he's unavailable or you're having trouble getting a response from him I'm happy to act as a backup.

**Comment by nmcb** [comment]
Thanks for the offer! We're definitely working on it. James has been a huge help setting up the SBT plugin infrastructure and integration with the PlayScala plugin at the beginning of the project. After that we got the code generation part into a prototypical state, with the focus on generating controller-, case-, validation- and test-classes from the swagger specification with Play integration having the normal incremental compilation. James hasn't been involved in that as the work basically consisted in trying to map the swagger specification onto a Play application if written by hand, so more from a user perspective than from a Play internal one. We're now stabilising the functionality which includes a major overhaul of the way we parse the swagger model, making it more strict and translating it into an internal representation of a Play application. Generation will also change drastically the next couple of months. This work is coded against the  [newnaming](https://github.com/zalando/play-swagger/commits/newnaming) branch, the master is mostly quiet at the moment.

**Comment by benmccann** [comment]
Thanks so much for the update. I sent a bunch of updates to [swagger-play](https://github.com/swagger-api/swagger-play), but after digging into it a bit and understanding it better, I think I like the approach this plugin is taking better. I'm thinking it could make sense for me to refocus my efforts by pitching in here instead.

I mostly use PlayJava and I see that you're targeting PlayScala. Would you be open to the idea of having the plugin be able to generate either Java or Scala code based on a setting in the plugin? I think you're already doing a lot of the work by parsing the spec and generating an internal representation. I'd be really interested in contributing if you're open to it.

I don't want to get in the way if it's not stable enough for that yet, but I might be able to at least lay some of the groundwork. E.g. just introducing the setting and having it only generate the routes file and no scala classes would make the plugin at least useful for us Java users even if not as featureful as the Scala version initially. There's also some other general stuff I might be able to help with that could benefit the Scala version while laying the groundwork for Java support. E.g. I think we could make it such that the plugin sets up the spec2 and scalacheck libraries so that the user doesn't have to edit their build file (and in the Java version we'd add junit instead).

**Comment by benmccann** [comment]
I'm going to file a new issue for the Java code generation to have an issue to track it. I don't expect you guys to do any real work towards Java support, but hopefully you don't mind me sending PRs for it. Supporting both Scala and Java I think it will help in getting more people using and testing the project and I think that a lot of the changes I would make would end up benefiting users of both.

**Comment by slavaschmidt** [comment]
Ben, sorry, for not coming back on you earlier. We are more then enthusiastic about Java code generation and your involvement into it. Marco and I talked today and we think that generating Java code could be a huge advantage for the project! We just trying to figure out a best way we could work together on that. Please give Marco some time to formulate some ideas about our ideas how we could support you in this regard.

**Comment by benmccann** [comment]
That's fantastic! I'm very excited!

**Comment by JosephEarl** [comment]
:+1: for Java support

**Pull request merged**
